name:                haskread-platform-manager
version:             0.1.0.0
github:              "tusharad/haskread-platform-manager"
license:             MIT
author:              "tushar"
maintainer:          "tusharadhatrao@gmail.com"
copyright:           "2025 tushar"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tusharad/haskread-platform-manager#readme>

dependencies:
- base >= 4.7 && < 5
- scotty
- text
- process
- req
- bytestring
- http-types
- unix
- scotty
- dhall
- filepath
- directory

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  haskread-platform-manager-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskread-platform-manager

tests:
  haskread-platform-manager-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskread-platform-manager
