name:                haskread-platform-ui
version:             0.1.0.0
github:              "tusharad/haskread-platform-ui"
license:             BSD-3-Clause
author:              "tushar"
maintainer:          "tusharadhatrao@gmail.com"
copyright:           "2024 tushar"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tusharad/haskread-platform-ui#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- string-conversions
- time
- http-api-data
- effectful-core
- hyperbole
- text
- http-conduit
- web-view
- bytestring
- hyperbole 
- wai-middleware-static 
- data-default-class >= 0.2
- data-default >= 0.8.0
- base64
- filepath

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  haskread-platform-ui-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskread-platform-ui

tests:
  haskread-platform-ui-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskread-platform-ui
