name:                haskread-platform-be
version:             0.1.0.0
github:              "tusharad/haskread-platform"
license:             MIT
author:              "tushar"
maintainer:          "tusharadhatrao@gmail.com"
copyright:           "2024 tushar"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tusharad/haskread-platform#readme>

dependencies:
- base >= 4.7 && < 5
- orville-postgresql
- text
- aeson
- servant-auth-server
- time
- mtl
- filepath
- bytestring
- servant-server
- bytestring
- warp
- haxl
- orville-postgresql
- unliftio
- time
- tasty
- hedgehog
- tasty-hedgehog
- tasty-hunit
- tasty-wai
- http-types
- string-interpolate
- servant-multipart
- http-api-data

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  haskread-platform-be-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskread-platform-be

tests:
  haskread-platform-be-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskread-platform-be
