name:                haskread-platform-be
version:             0.1.0.0
github:              "tusharad/haskread-platform"
license:             MIT
author:              "tushar"
maintainer:          "tusharadhatrao@gmail.com"
copyright:           "2024 tushar"

extra-source-files:
- README.md
- CHANGELOG.md

description: Core backend service of haskread platform

dependencies:
- base >= 4.7 && < 5
- orville-postgresql
- text
- aeson
- servant-auth-server
- time
- mtl
- filepath
- bytestring
- servant-server
- bytestring
- warp
- haxl
- orville-postgresql
- unliftio
- time
- hedgehog
- http-types
- string-interpolate
- servant-multipart
- http-api-data
- fast-logger
- dhall
- directory
- password
- hashable
- async
- req
- string-interpolate
- random
- hoauth2
- hoauth2-providers
- uri-bytestring
- containers
- transformers
- http-conduit
- wai-cors
- wai
- http-media
- unix
- uuid
- wai-rate-limit
- sqlite-simple
- google-cloud-storage

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  haskread-platform-be-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskread-platform-be

tests:
  haskread-platform-be-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskread-platform-be
    - tasty
    - tasty-hedgehog
    - tasty-hunit
    - tasty-wai
    - servant-multipart
