name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    
    - name: Copy repo into actions 
      uses: actions/checkout@v3
    
    - name: Start test database
      run: make startTestDB
    
    - name: install dependancies, build and test stack project.
      uses: freckle/stack-cache-action@v5

    - name: stop test database
      run: make stopTestDB
