name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  MailFromEmail : ${{ vars.MailFromEmail }}
  MailAPIToken : ${{ secrets.MailAPIToken }}
  GoogleOAuth2ClientID : ${{ secrets.GoogleOAuth2ClientID }}
  GoogleOAuth2ClientSecret : ${{ secrets.GoogleOAuth2ClientSecret }}
  HaskReadJwtSecret : ${{ secrets.HaskReadJwtSecret }}

jobs:
  build-ui:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: ./haskread-platform-ui/

    steps:
    
    - name: Copy repo into actions 
      uses: actions/checkout@v3
    
    - name: install dependancies, build and test stack project.
      uses: freckle/stack-action@v5
      with:
        working-directory: ./haskread-platform-ui/
        stack-build-arguments: --copy-bins --ghc-options="-fno-warn-unused-imports -fno-warn-unused-matches -fno-warn-type-defaults -fno-warn-missing-export-lists"
        stack-build-arguments-test: --ghc-options="-fno-warn-unused-imports -fno-warn-unused-matches -fno-warn-type-defaults -fno-warn-missing-export-lists"

    - name: upload ui binary
      uses: actions/upload-artifact@v4
      with:
          name: ui-binary
          path: /home/runner/.local/bin/haskread-platform-ui-exe

  build-be:
    environment: Test Env
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: ./haskread-platform-be/

    steps:
    
    - name: Copy repo into actions 
      uses: actions/checkout@v3
    
    - name: Start test database
      run: make startTestDB
    
    - name: install dependancies, build and test stack project.
      uses: freckle/stack-action@v5
      with:
        working-directory: ./haskread-platform-be/
        stack-build-arguments: --copy-bins --ghc-options="-fno-warn-unused-imports -fno-warn-unused-matches -fno-warn-type-defaults -fno-warn-missing-export-lists"
        stack-build-arguments-test: --ghc-options="-fno-warn-unused-imports -fno-warn-unused-matches -fno-warn-type-defaults -fno-warn-missing-export-lists"

    - name: upload be binary
      uses: actions/upload-artifact@v4
      with:
          name: be-binary
          path: /home/runner/.local/bin/haskread-platform-be-exe

    - name: stop test database
      run: make stopTestDB

  deploy:
    needs : [build-be, build-ui]
    environment: Test Env
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Upload UI binary to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: ./artifacts
          destination: haskread_ci_storage
      
      - name: Deploying code
        run: |
          curl --request POST \
            --url https://haskread.tushar-adhatrao.in/api/service/app/update \
            --header 'Authorization: Bearer ${{ secrets.BEARER_TOKEN }}'